### ISSUE TITLE
Error calcASE() with no normalCells

### ISSUE THREAD

**Issue by Gregory94** [constantAmateur/alleleIntegrator#1]
Hi,

When running the function `calcASE()` with just the `gCnts` object and no `normalCells` specified, the following error occurs:

`Error in if (abs(tmp - 0.5) > 0.2) warning(sprintf("%d of %d have ASE greater than 0.5.  Your normal cells are probably not normal.  Consider running without normalCells.",  : 
  missing value where TRUE/FALSE needed`

When looking at the code this makes sense as the `priorKappa` value is set to `Inf` when no normalCells are specified. As a result of that the `priorKappa` is never recalculated by the function `calcPriorASE()`. Then, when `dd$matFrac` is determined, there is a division by Inf which causes NaN values to occur in `dd` and ultimately in `tmp`, causing the above error.

Best,
Gregory

**Comment by constantAmateur** [comment]
Thank you for outlining this issue in such detail.  The newest version 0.8.8, should fix this problem.
